# Generated by Django 3.1.7 on 2021-04-09 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=400)),
                ('date', models.DateField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=300)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('loc_hint', models.CharField(max_length=300)),
                ('email', models.CharField(default='aaa', max_length=30)),
            ],
            options={
                'db_table': 'contact_details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_type', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('housename', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('emial_Id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('logintype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('campany', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('housename', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('emial_Id', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('conf_password', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.login')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Sales_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('total_amount', models.FloatField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.patient')),
            ],
            options={
                'db_table': 'sales_master',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('from_time', models.TimeField(max_length=50)),
                ('to_time', models.TimeField(max_length=50)),
                ('fee', models.CharField(default='100', max_length=50)),
                ('EMPPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.employee')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=400)),
                ('date', models.DateField(max_length=50)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=400)),
                ('date', models.DateField(max_length=50)),
            ],
            options={
                'db_table': 'tips',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('exp_date', models.DateField(max_length=100)),
                ('man_date', models.DateField(max_length=50)),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.medicine')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField(max_length=50)),
                ('slot_status', models.CharField(max_length=50)),
                ('SCHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.schedule')),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.CreateModel(
            name='Sales_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.medicine')),
                ('SALE_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.sales_master')),
            ],
            options={
                'db_table': 'sales_sub',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_date', models.DateField(max_length=300)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.booking')),
            ],
            options={
                'db_table': 'reminder',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=50)),
                ('does', models.CharField(max_length=50)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.booking')),
                ('MEDICINE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.medicine')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('reason', models.TextField(max_length=100)),
                ('leave_status', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=100)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.employee')),
            ],
            options={
                'db_table': 'leave',
            },
        ),
        migrations.CreateModel(
            name='Late_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('arriving_time', models.TimeField(max_length=50)),
                ('EMPPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.employee')),
            ],
            options={
                'db_table': 'late_message',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('feedback', models.CharField(max_length=200)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.patient')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.login'),
        ),
        migrations.CreateModel(
            name='Current_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('current_slot', models.CharField(max_length=50)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.employee')),
            ],
            options={
                'db_table': 'current_slot',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='EMPLOYEE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='PATIENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.patient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='SLOT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.slot'),
        ),
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=400)),
                ('from_time', models.CharField(default='00:00', max_length=200)),
                ('to_time', models.CharField(default='00:00', max_length=200)),
                ('status', models.CharField(default='absent', max_length=200)),
                ('EMPLOYEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daya_clinic.employee')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
